import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import Saly from "../public/Saly.png";
import avatar from "../public/avatar.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Raynelz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbyraynelz</h1>
            <ul className="flex items.centre">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Zakhar Litvinchuk
            </h2>
            <h3 className="text-2xl py-2">React Developer.</h3>
            <p className="text-md py-5 leading-8 text-grey-800">
              I m a Web-developer with 1 year of experience.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillGithub />
            <AiFillLinkedin />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mtt-20 overflow-hidden">
            <Image src={avatar} alt="avatar" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beggining of my journey as a frontend devloper, I have
              done projects for
              <span className=" text-teal-500"> hackaton </span>
              or for myself <span className=" text-teal-500">
                projects
              </span>{" "}
              that I have done just for fun.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              {" "}
              I love programmimg much as i can.
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Betiful Websites
              </h3>
              <p className="py-2">
                Code elegant and minimalistic websites for your needs.
              </p>
              <h4 className="py-4 text-teal-600">Code tools I use</h4>
              <p className=" text-gray-800">React</p>
              <p className=" text-gray-800">NextJS</p>
              <p className=" text-gray-800">Tailwind</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} alt="design" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Betiful Websites
              </h3>
              <p className="py-2">
                Code elegant and minimalistic websites for your needs.
              </p>
              <h4 className="py-4 text-teal-600">Code tools I use</h4>
              <p className=" text-gray-800">React</p>
              <p className=" text-gray-800">NextJS</p>
              <p className=" text-gray-800">Tailwind</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
